Hello World

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,5 +1,17 @@
 #!/bin/bash
 
-# Run the Python script using the value of PYFILE
+# Check if PYFILE environment variable is set
+if [ -z "$PYFILE" ]; then
+  echo "PYFILE environment variable is not set."
+  exit 1
+fi
+
+# Check if the specified Python file exists
+if [ ! -f "$PYFILE" ]; then
+  echo "Python file $PYFILE not found."
+  exit 1
+fi
+
+# Run the Python script
 python3 "$PYFILE"
 
